steps:
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - >-
        git clone "https://github.com/nytimes/library.git" && cd library && mv ../.env .env && sed -i 's/"node": ">=10.x"/"node": "10.x"/g' package.json && perl -i -p -e 's/ACCESSJSON/$$ENV{ACCESS_JSON}/g' .env && sed -i "s/CLIENTSECRET/$$CLIENT_SECRET/g" .env && sed -i "s/GITHUBSECRET/$$GITHUB_SECRET/g" .env && sed -i "s/SESSIONSECRET/$$SESSION_SECRET/g" .env && cat .env
    entrypoint: bash
    secretEnv:
      - ACCESS_JSON
      - CLIENT_SECRET
      - GITHUB_SECRET
      - SESSION_SECRET
  - name: node
    args:
      - '-c'
      - cd library && npm install && npm run gcp-build
    entrypoint: bash
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - cd library && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy
    entrypoint: bash
timeout: 1600s
availableSecrets:
  secretManager:
    - versionName: projects/925975218883/secrets/library-access-json/versions/1
      env: ACCESS_JSON
    - versionName: projects/925975218883/secrets/library-client-secret/versions/1
      env: CLIENT_SECRET
    - versionName: projects/925975218883/secrets/github-customization-secret/versions/1
      env: GITHUB_SECRET
    - versionName: projects/925975218883/secrets/session-secret/versions/1
      env: SESSION_SECRET
